// <auto-generated />
using System;
using LabArquitetura.Infrastructure.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabArquitetura.Migrations
{
    [DbContext(typeof(LabArquiteturaDbContext))]
    [Migration("20230212005124_AddEndereco")]
    partial class AddEndereco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("LabArquitetura.Infrastructure.Repositories.Models.FuncionarioDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("CHAR(11)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("LabArquitetura.Infrastructure.Repositories.Models.QueueDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referrer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("LabArquitetura.Infrastructure.Repositories.Models.FuncionarioDbModel", b =>
                {
                    b.OwnsOne("core.Models.ValueObjects.Endereco", "EnderecoCorrespondencia", b1 =>
                        {
                            b1.Property<string>("FuncionarioDbModelId")
                                .HasColumnType("VARCHAR(36)");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("TEXT");

                            b1.HasKey("FuncionarioDbModelId");

                            b1.ToTable("Funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioDbModelId");
                        });

                    b.OwnsOne("core.Models.ValueObjects.Endereco", "EnderecoPrincipal", b1 =>
                        {
                            b1.Property<string>("FuncionarioDbModelId")
                                .HasColumnType("VARCHAR(36)");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("TEXT");

                            b1.HasKey("FuncionarioDbModelId");

                            b1.ToTable("Funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioDbModelId");
                        });

                    b.Navigation("EnderecoCorrespondencia");

                    b.Navigation("EnderecoPrincipal");
                });
#pragma warning restore 612, 618
        }
    }
}
